idp_todo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

current_version = 'todo_v0'

urlpatterns = [
    url(r'^', include( current_version + '.urls')),
    url(r'^admin/', admin.site.urls),
]

todo_v0/urls.py
from django.conf.urls import url

from django.views.decorators.csrf import csrf_exempt

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mark_done/(?P<id>\d+)/$', views.mark_done, name="mark_done"),
    url(r'^mark_todo/(?P<id>\d+)/$', views.mark_todo, name="mark_todo"),
    url(r'^new_todo/$', views.new_todo, name="new_todo")
]

todo_v0/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models

# Create your models here.
@python_2_unicode_compatible
class TodoItem(models.Model): 
    id = models.AutoField(primary_key=True)
    txt = models.CharField(max_length=1000)
    color = models.CharField(max_length=12)
    done = models.BooleanField(default=False)

    def __str__(self):
        return "[%s] %s" % (self.id, self.txt)

todo_v0/forms.py
from django import forms

class NewTodoForm(forms.Form):
    new_item_txt = forms.CharField(label='', max_length=1000, widget=forms.TextInput(attrs={'placeholder': 'todo'}) )
    # new_item_color = forms.CharField(label='', max_length=12, required=False, widget=forms.TextInput(attrs={'placeholder': 'color'}) )

todo_v0/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from helpers import random_color

# import models
from .models import TodoItem

#import forms
from .forms import NewTodoForm



# Create your views here.


def index(request):

    todo_list = TodoItem.objects.filter(done=False)
    done_list = TodoItem.objects.filter(done=True)

    form = NewTodoForm()

    return render(request, 'index.html', locals())

def mark_done(request, id):

    done_item = TodoItem.objects.get(id=id)
    done_item.done = True
    done_item.save()

    return redirect('/')

def mark_todo(request, id):
    done_item = TodoItem.objects.get(id=id)
    done_item.done = False
    done_item.save()

    return redirect('/')

def new_todo(request):
    if request.method == 'POST':
        form = NewTodoForm(request.POST)
        if form.is_valid():
            todo_txt = form.cleaned_data['new_item_txt']

            new_item = TodoItem()
            new_item.txt = todo_txt
            new_item.color = random_color()

            new_item.save()

    return redirect('/')

todo_v0/templates/index.html
<html>

    <head>
        <title>-- todo --</title>
    </head>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Roboto+Mono');
        body {font-family: 'Roboto Mono', monospace;}

        .main-container{
            margin-top: 5em; 
        }
        ul{
            max-width: 500;
            list-style: none;
            text-align: left;
        }
        li{
            padding: .5em;
            border: solid 1px #F0F0F0;
            border-radius: .3em;
            text-align: left;
            margin-bottom: .5em;
            border-left-width: .5em;
            cursor: pointer;
        }
        li:hover{
            background-color: #F0F0F0;
        }
        #new-item-img{
            position: absolute;
            width: 80px;
            right: .5em;
            bottom: .5em;
        }
        #new-item-prompt{
            display: none;
            position: absolute;
            bottom: .5em;
            right: calc(.5em + 80px);
            border: 1px solid #F0F0F0;
            padding: .4em;
            width: 300px;
            border-radius: .3em;
            box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
        }
        #new_item_txt{
            width: 100%;
            margin-bottom: .5em
        }
        input{
            margin-bottom: .5em;
            padding: .3em;
            display: block;
        }
        #id_new_item_txt{

            width: 100%;
        }
        #new-item:hover #new-item-prompt{
            display: block;
        }
        a{
            text-decoration: none;
            color: black; 
        }
        #new-item-title{
            margin: 0;
            padding: 0;
            text-align: center;
            margin-top: .5em;
            margin-bottom: .5em;

        }
    </style>

    <body>

        <div class="main-container">
            <center>
                <h3>Todo list</h3>
                <!-- <img src="">  -->
                <div>
                    
                    <ul>
                        <h4>TODO</h4>
                        {% for item in todo_list %}
                            <a href="/mark_done/{{item.id}}/">
                                <li style="border-left-color:{{item.color}}" >
                                    {{ item.txt }}
                                </li>  
                            </a>
                        {% endfor %}
                    </ul>
                    <ul>
                        <h4>DONE</h4>
                            {% for item in done_list %}
                                <a href="/mark_todo/{{item.id}}/">
                                    <li style="border-left-color:{{item.color}}" >
                                        {{ item.txt }}
                                    </li>  
                                </a>
                            {% endfor %}
                        </ul>
                </div>
            </center>

            <div id="new-item">
                <img src="https://media.giphy.com/media/3o7aCQNE8LAwzhucRW/giphy.gif" id="new-item-img">
                <div id="new-item-prompt">
                    <h4 id="new-item-title">Add new</h4>
                    <form action="/new_todo/" method="post">
                        {% csrf_token %}
                        {{ form }}
                    </form>
                </div>
            </div>

            

        </div>

    </body>

</html>